'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';
import { ToolFrame } from '@/components/tool-frame';
import { cutPlan, imageSizeError, type Cut } from '@/lib/screenshot-cuts';
type Source = { image: HTMLImageElement; url: string; name: string; width: number; height: number };
function paint(canvas: HTMLCanvasElement, source: Source, cuts: Cut[], preview: boolean) {
  const plan = cutPlan(source.height, cuts, Math.min(200, Math.max(28, Math.round(source.width * .035))));
  const scale = preview ? Math.min(1, 1000 / source.width, 2200 / plan.height) : 1;
  canvas.width = Math.max(1, Math.round(source.width * scale)); canvas.height = Math.max(1, Math.round(plan.height * scale));
  const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Your browser could not create an image.'); ctx.scale(scale, scale);
  for (const p of plan.parts) {
    if (p.kind === 'keep') ctx.drawImage(source.image, 0, p.start, source.width, p.height, 0, p.outputY, source.width, p.height);
    else { ctx.fillStyle = '#edf2fb'; ctx.fillRect(0, p.outputY, source.width, p.height); ctx.fillStyle = '#345175'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.font = `${Math.max(10, Math.round(p.height * .42))}px Arial`; ctx.fillText('··· content omitted ···', source.width / 2, p.outputY + p.height / 2, source.width * .9); }
  } return plan;
}
export default function Review() {
  const [source, setSource] = useState<Source | null>(null), [cuts, setCuts] = useState<(Cut & { id: number })[]>([]);
  const [start, setStart] = useState(0), [end, setEnd] = useState(1), [editing, setEditing] = useState<number | null>(null), [firstPoint, setFirstPoint] = useState<number | null>(null);
  const [zoom, setZoom] = useState(100), [message, setMessage] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const preview = useRef<HTMLCanvasElement>(null), request = useRef(0), nextId = useRef(1);
  useEffect(() => () => { if (source) URL.revokeObjectURL(source.url); }, [source]);
  const planResult = useMemo(() => { try { return { plan: source ? cutPlan(source.height, cuts, Math.min(200, Math.max(28, Math.round(source.width * .035)))) : null, error: '' }; } catch (e) { return { plan: null, error: (e as Error).message }; } }, [source, cuts]);
  useEffect(() => { if (!source || !preview.current || !planResult.plan) return; try { paint(preview.current, source, cuts, true); } catch (e) { setError((e as Error).message); } }, [source, cuts, planResult]);
  async function openFile(file?: File) {
    if (!file) return; const id = ++request.current; setError(''); setBusy(true); setMessage('Opening image…'); let url = '';
    try {
      if (!/\.(png|jpe?g|webp)$/i.test(file.name) || file.size > 20 * 1024 * 1024) throw new Error('Choose a PNG, JPG, or WebP up to 20 MB. Use a still image.');
      url = URL.createObjectURL(file); const image = new Image(); image.src = url; await image.decode(); const sizeError = imageSizeError(image.naturalWidth, image.naturalHeight); if (sizeError) throw new Error(sizeError);
      if (id !== request.current) { URL.revokeObjectURL(url); return; }
      setSource({ image, url, name: file.name, width: image.naturalWidth, height: image.naturalHeight }); setCuts([]); setStart(0); setEnd(Math.max(1, Math.floor(image.naturalHeight / 5))); setEditing(null); setFirstPoint(null); setZoom(100); setMessage('Mark a section on the original, then add the cut.');
    } catch (e) { if (url) URL.revokeObjectURL(url); if (id === request.current) { setError((e as Error).message); setMessage(''); } } finally { if (id === request.current) setBusy(false); }
  }
  function addCut() {
    if (!source) return; const next = editing === null ? [...cuts, { start, end, id: nextId.current++ }] : cuts.map(c => c.id === editing ? { ...c, start, end } : c);
    try { if (next.length > 30) throw new Error('Use up to 30 cuts per image.'); cutPlan(source.height, next); setCuts(next); setEditing(null); setFirstPoint(null); setError(''); setMessage('Cut saved. Add another or adjust a saved cut.'); } catch (e) { setError((e as Error).message); }
  }
  async function download() {
    if (!source || !cuts.length || !planResult.plan) return; setBusy(true); setError('');
    try { const canvas = document.createElement('canvas'); paint(canvas, source, cuts, false); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob(b => b ? resolve(b) : reject(new Error('Could not save this image. Try a smaller screenshot.')), 'image/png')); canvas.width = canvas.height = 0; const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = source.name.replace(/\.[^.]+$/, '') + '-shortened.png'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 30000); setMessage('PNG ready. Your original file is unchanged.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <ToolFrame current="/screenshot-cut-review" number="003 / IMAGES" title="Screenshot cut review" intro="Remove several middle sections. Keep the original in view.">
    <section className="file-pick"><label htmlFor="screenshot-file">Choose a screenshot<Input id="screenshot-file" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e => { void openFile(e.target.files?.[0]); e.target.value = ''; }} /></label><p>PNG, JPG, or still WebP · up to 20 MB and 12 million pixels · no upload</p></section>
    {source ? <>
      <section className="cut-controls review" aria-label="Cut controls"><div className="review-heading"><div><h2>{editing === null ? 'Mark a section to remove' : 'Adjust saved cut'}</h2><p>Positions refer to the original image. Start is included; end is excluded.</p></div><Button variant="outline" onClick={() => { setCuts([]); setEditing(null); setFirstPoint(null); setError(''); setMessage('All cuts cleared.'); }}>Restore all</Button></div><div className="control-body"><div className="number-row"><label>Start pixel<Input type="number" min={0} max={source.height - 1} value={start} onChange={e => setStart(Number(e.target.value))} /></label><label>End pixel<Input type="number" min={1} max={source.height} value={end} onChange={e => setEnd(Number(e.target.value))} /></label><Button onClick={addCut}>{editing === null ? 'Add cut' : 'Update cut'}</Button>{editing !== null && <Button variant="outline" onClick={() => { setEditing(null); setFirstPoint(null); }}>Cancel edit</Button>}</div><Slider aria-label="Cut start and end" min={0} max={source.height} step={1} value={[Math.min(start, end), Math.max(start, end)]} onValueChange={v => { const [a, b] = v as number[]; setStart(a); setEnd(b); setFirstPoint(null); }} /><p className="small-note">Or tap two positions on the original to mark a section. Blue is your draft; red shows saved cuts.</p><div className="cut-list">{cuts.map((c, i) => <div key={c.id} className="cut-chip"><span>Cut {i + 1}: {c.start}–{c.end} px</span><Button variant="ghost" onClick={() => { setStart(c.start); setEnd(c.end); setEditing(c.id); setFirstPoint(null); }}>Edit</Button><Button variant="ghost" aria-label={`Remove cut ${i + 1}`} onClick={() => { setCuts(cuts.filter(x => x.id !== c.id)); if (editing === c.id) setEditing(null); setError(''); }}>×</Button></div>)}</div></div></section>
      <div className="matching-rules"><label>Original zoom <Input className="zoom-input" type="number" min={25} max={300} step={25} value={zoom} onChange={e => setZoom(Math.max(25, Math.min(300, Number(e.target.value) || 100)))} /> %</label><span>{source.width} × {source.height} px</span></div>
      <section className="workspace image-comparison"><div className="editor-panel"><div className="panel-top"><strong>Original · mark two positions</strong><span>{firstPoint !== null ? 'Tap the end position' : 'Tap the start position'}</span></div><div className="image-scroll"><div className="cut-source" style={{ width: Math.min(source.width, 650) * zoom / 100 }} onClick={e => { const r = e.currentTarget.getBoundingClientRect(); const y = Math.max(0, Math.min(source.height, Math.round((e.clientY - r.top) / r.height * source.height))); if (firstPoint === null) { setFirstPoint(y); setStart(Math.min(y, source.height - 1)); setEnd(Math.min(source.height, y + 1)); } else { setStart(Math.min(firstPoint, y)); setEnd(Math.max(firstPoint, y)); setFirstPoint(null); } }}><img src={source.url} alt="Original screenshot for selecting cut positions" draggable={false} />{cuts.map(c => <div key={c.id} className="cut-overlay saved-cut" style={{ top: `${c.start / source.height * 100}%`, height: `${(c.end - c.start) / source.height * 100}%` }} />)}{start >= 0 && end > start && end <= source.height && <div className="cut-overlay draft-cut" style={{ top: `${start / source.height * 100}%`, height: `${(end - start) / source.height * 100}%` }} />}</div></div></div><div className="editor-panel result-panel"><div className="panel-top"><strong>Result · saved cuts only</strong><span>{planResult.plan ? `${source.width} × ${planResult.plan.height} px` : 'Check cuts'}</span></div><div className="image-scroll result-image"><canvas ref={preview} aria-label="Preview with saved sections removed and omission markers inserted" /></div></div></section>
      <div className="panel-bottom export-row"><span>{planResult.plan ? `${planResult.plan.removed} original rows removed · ${planResult.plan.merged.length} omission markers` : ''}. Touching or overlapping cuts are combined.</span><Button onClick={download} disabled={busy || !cuts.length || !planResult.plan}>{busy ? 'Preparing…' : 'Download PNG'}</Button></div>
    </> : <div className="empty-workspace"><h2>One screenshot. Several cuts.</h2><p>Choose an image, mark the sections you do not need, and check the shorter version before saving.</p><div className="sequence-demo"><span>Keep A</span><span className="omission-demo">content omitted</span><span>Keep B</span><span className="omission-demo">content omitted</span><span>Keep C</span></div></div>}
    {(error || planResult.error) && <p role="alert" className="error">{error || planResult.error}</p>}<p role="status" className="status">{message}</p>
    <div className="notes-grid"><section><p className="eyebrow">HOW TO USE</p><h2>Mark, review, save.</h2><ol><li>Choose a screenshot. Tap two positions or enter pixel boundaries, then add the cut.</li><li>Add more sections. Use Edit or × to correct a cut, and zoom in to check text near a boundary.</li><li>Download the result. Visible omission markers identify the removed sections; the original stays unchanged.</li></ol></section><section><p className="eyebrow">WHERE IT STOPS</p><h2>You choose what to leave out.</h2><p>This tool removes full-width horizontal bands from one still image. It does not detect ads, reconstruct backgrounds, or check for private information. Review the remaining text and its meaning before sharing.</p><p>Output keeps the original width. Preview is scaled to fit; PNG file size may increase. Very long images may need a smaller source on a phone. Animated files are not supported.</p></section></div><details className="privacy"><summary>What happens to my image?</summary><p>The image is processed in this tab and is not uploaded or saved in browser storage by the tool. Reloading clears your work. Ordinary page requests and external links still have their own privacy policies.</p></details>
  </ToolFrame>;
}
