'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { ToolFrame } from '@/components/tool-frame';
import { basename, candidateVideos, collisionNames, episodeKey, EXAMPLE_VIDEOS, filenameError, proposedName, subtitleTags } from '@/lib/subtitle-pairs';
type Row = { file: File; video: number; name: string; confirmed: boolean };
const allowed = /\.(srt|ass|ssa|vtt|sub)$/i;
export default function Review() {
  const [videoText, setVideoText] = useState(''), [rows, setRows] = useState<Row[]>([]), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const videos = videoText.split(/\r\n?|\n/).map(x => basename(x.trim())).filter(Boolean);
  const videoError = videos.length > 100 || videoText.length > 30000 ? 'Use up to 100 video names and 30,000 characters.' : '';
  const collisions = collisionNames(rows.filter(r => r.video >= 0 && r.name).map(r => r.name));
  const issue = (r: Row) => r.video < 0 || !videos[r.video] ? 'Choose the matching video.' : filenameError(r.name, r.file.name.split('.').at(-1)!) || (collisions.has(r.name.normalize('NFC').toLowerCase()) ? 'Output name collision. Change a name or remove an extra subtitle.' : '');
  const confirmed = rows.filter(r => r.confirmed && !issue(r));
  function makeRows(files: File[], sourceVideos: string[]) { return files.map(file => { const candidates = candidateVideos(file.name, sourceVideos); const video = candidates.length === 1 ? candidates[0] : -1; return { file, video, name: video < 0 ? '' : proposedName(sourceVideos[video], file.name, subtitleTags(file.name)), confirmed: false }; }); }
  function changeVideos(value: string) { setVideoText(value); const next = value.split(/\r\n?|\n/).map(x => basename(x.trim())).filter(Boolean); setRows(makeRows(rows.map(r => r.file), next)); setMessage('Video names changed. Review and confirm the new pairings.'); setError(''); }
  function loadFiles(files: File[]) {
    if (!files.length) return;
    if (files.length > 100 || files.some(f => !allowed.test(f.name) || f.size > 2 * 1024 * 1024) || files.reduce((n, f) => n + f.size, 0) > 25 * 1024 * 1024) { setError('Choose up to 100 SRT, ASS, SSA, VTT, or text SUB files, at most 2 MB each and 25 MB total.'); return; }
    setRows(makeRows(files, videos)); setError(''); setMessage('Suggestions are not confirmed. Check the episode, language, and output name for each subtitle.');
  }
  function example() { setVideoText(EXAMPLE_VIDEOS); const names = ['review.1x01.en.srt', 'review.S01E01.fr.forced.srt', 'review.S01E03.en.srt', 'review.S01E04.en.srt', 'English.srt']; const files = names.map(n => new File(['1\n00:00:01,000 --> 00:00:03,000\nSynthetic example subtitle.\n'], n, { type: 'text/plain' })); setRows(makeRows(files, EXAMPLE_VIDEOS.split('\n'))); setError(''); setMessage('Synthetic example loaded: two unique suggestions, a missing episode, an ambiguous episode, and a name with no episode.'); }
  function update(index: number, patch: Partial<Row>) { setRows(rows.map((r, i) => i === index ? { ...r, ...patch } : r)); setMessage(''); }
  async function download() {
    if (!confirmed.length || videoError) return; setBusy(true); setError('');
    try { const { zipSync } = await import('fflate'); const files: Record<string, Uint8Array> = Object.create(null); for (const r of confirmed) files[r.name] = new Uint8Array(await r.file.arrayBuffer()); const zipped = zipSync(files, { level: 0 }); const url = URL.createObjectURL(new Blob([zipped as BlobPart], { type: 'application/zip' })); const a = document.createElement('a'); a.href = url; a.download = 'hwanseek-subtitle-copies.zip'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 30000); setMessage(`ZIP ready with ${confirmed.length} confirmed subtitle copies. Put them beside the matching videos after extracting.`); } catch { setError('Could not create the ZIP. Try fewer or smaller files.'); } finally { setBusy(false); }
  }
  return <ToolFrame current="/subtitle-pair-review" number="004 / FILES" title="Subtitle pair review" intro="Check the episode. Confirm the name. Save subtitle copies.">
    <section className="workspace"><div className="editor-panel"><div className="panel-top"><label htmlFor="video-names">1 · Video filenames</label><Button variant="ghost" disabled={busy} onClick={example}>Load example</Button></div><Textarea id="video-names" value={videoText} disabled={busy} placeholder={'Example.Show.S01E01.mkv\nExample.Show.S01E02.mkv'} onChange={e => changeVideos(e.target.value)} spellCheck={false} /><div className="control-body"><label className="small-note">Or select video files — names only<Input type="file" multiple disabled={busy} accept="video/*,.mkv,.mp4,.avi,.mov,.webm,.m4v,.ts" onChange={e => { changeVideos(Array.from(e.target.files || []).map(f => f.name).join('\n')); e.target.value = ''; }} /></label></div></div><div className="editor-panel result-panel"><div className="panel-top"><label htmlFor="subtitle-files">2 · Subtitle files</label><span>{rows.length} selected</span></div><div className="control-body"><Input id="subtitle-files" type="file" accept=".srt,.ass,.ssa,.vtt,.sub" multiple disabled={busy} onChange={e => { loadFiles(Array.from(e.target.files || [])); e.target.value = ''; }} /><p className="small-note">Up to 100 files · 2 MB each · 25 MB total. Video content is never read. Subtitle contents are copied unchanged.</p><p className="small-note">Suggestions use S01E01 or 1x01 episode numbers. Same episode numbers in different shows can match, so review the title too. Folder context and language are not reliably inferred.</p></div></div></section>
    {(error || videoError) && <p role="alert" className="error">{error || videoError}</p>}
    {rows.length > 0 && <section className="review"><div className="review-heading"><div><h2>3 · Review and confirm</h2><p>{confirmed.length} of {rows.length} files ready. Only confirmed, valid rows go in the ZIP.</p></div><Button disabled={busy || !confirmed.length || !!videoError} onClick={download}>{busy ? 'Preparing…' : `Download ${confirmed.length} copies`}</Button></div><div className="pair-list">{rows.map((r, i) => { const candidates = candidateVideos(r.file.name, videos); const problem = issue(r); return <article key={i} className="pair-row"><div className="pair-original"><strong>{r.file.name}</strong><p>{!episodeKey(r.file.name) ? 'No single supported episode number: choose manually.' : !candidates.length ? 'No video has this episode number.' : candidates.length > 1 ? `${candidates.length} videos share this episode number: choose manually.` : 'One episode candidate. Check the show and language.'}</p><Button variant="ghost" disabled={busy} onClick={() => setRows(rows.filter((_, j) => i !== j))}>Remove file</Button></div><div><label htmlFor={`video-${i}`}>Matching video</label><NativeSelect id={`video-${i}`} value={r.video} disabled={busy || !!videoError} onChange={e => { const video = Number(e.target.value); update(i, { video, name: video < 0 ? '' : proposedName(videos[video], r.file.name, subtitleTags(r.file.name)), confirmed: false }); }}><NativeSelectOption value={-1}>Choose a video…</NativeSelectOption>{videos.slice(0, 100).map((v, vi) => <NativeSelectOption value={vi} key={vi}>{v}</NativeSelectOption>)}</NativeSelect><label htmlFor={`name-${i}`}>Output filename · check language / forced / SDH</label><Input id={`name-${i}`} value={r.name} disabled={busy || r.video < 0} onChange={e => update(i, { name: e.target.value, confirmed: false })} spellCheck={false} />{problem && <p className="row-warning">{problem}</p>}<label className="confirm-row"><Checkbox checked={r.confirmed && !problem} disabled={busy || !!problem || !!videoError} onCheckedChange={v => update(i, { confirmed: v === true })} />I checked this pairing and output name</label></div></article>; })}</div></section>}
    <p role="status" className="status">{message}</p><div className="notes-grid"><section><p className="eyebrow">HOW TO USE</p><h2>Make the names agree.</h2><ol><li>Paste video filenames, one per line, or select videos to read only their names.</li><li>Select subtitle files. Review suggestions and choose manually when the episode is missing or ambiguous.</li><li>Keep language and forced/SDH labels in output names. Confirm each pairing, download the ZIP, and put extracted files beside the videos.</li></ol></section><section><p className="eyebrow">WHERE IT STOPS</p><h2>A filename is a clue.</h2><p>This tool does not watch videos, inspect subtitle language, fix timing, translate, or change subtitle encoding. It cannot infer an episode from English.srt alone. Multi-episode names and other naming styles need manual selection.</p><p>Names are checked for common Windows restrictions and case-insensitive collisions. Player naming rules vary. VobSub IDX/SUB pairs and other multi-file subtitle formats are not supported; choose text SUB files only.</p></section></div><details className="privacy"><summary>What happens to my files?</summary><p>Names and subtitle bytes stay in this browser tab. The tool creates a ZIP of renamed copies; it does not overwrite the originals or upload files. Reloading clears your work. Ordinary page requests and external links have their own policies.</p></details>
  </ToolFrame>;
}
