'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ToolFrame} from '@/components/tool-frame';
import {Button} from '@/components/ui/button';
import {matchList,rowSelection,unresolved,selectedPaths,bundleProblem,makeReport,createBundle,MAX_INDEX,type LocalEntry,type MatchRow,type Choices} from '@/lib/file-list-pick';
import './style.css';

function size(n:number){return n<1024?`${n} bytes`:`${(n/1024/1024).toFixed(2)} MiB`;}
function save(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export default function Review(){
  const [entries,setEntries]=useState<LocalEntry[]>([]),[folder,setFolder]=useState(''),[text,setText]=useState(''),[rows,setRows]=useState<MatchRow[]|null>(null),[choices,setChoices]=useState<Choices>({}),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<Blob|null>(null),[filter,setFilter]=useState('all'),[page,setPage]=useState(0);
  const picker=useRef<HTMLInputElement>(null),abort=useRef<AbortController|null>(null);
  useEffect(()=>()=>abort.current?.abort(),[]);
  function invalidate(){setRows(null);setChoices({});setAck(false);setResult(null);setMessage('');setError('');setPage(0);setFilter('all');}
  function example(){invalidate();const items=[['Team A/notes.txt','Example notes from Team A.\n'],['Team B/notes.txt','Example notes from Team B.\n'],['Documents/Project brief.txt','Synthetic project brief. No private information.\n'],['Documents/선택.txt','연습용 텍스트 파일입니다.\n']];setEntries(items.map(([path,content])=>{const file=new Blob([content]);return {path,name:path.split('/').at(-1)!,size:file.size,file};}));setFolder('Example files (synthetic)');setText('notes.txt\nProject brief.txt\n선택.txt\nmissing.txt\nProject brief.txt');if(picker.current)picker.current.value='';setMessage('Synthetic example loaded. Review matches, then choose which notes.txt to include.');}
  function choose(files:FileList|null){if(!files?.length)return;invalidate();if(files.length>MAX_INDEX){setEntries([]);setFolder('');setError('Choose a folder with at most 10,000 files. No partial folder was loaded.');return;}const list=Array.from(files);const root=list[0].webkitRelativePath.split('/')[0];if(!root||list.some(f=>!f.webkitRelativePath.startsWith(root+'/'))){setEntries([]);setFolder('');setError('Folder selection is not supported here. Use a current desktop browser.');return;}setFolder(root);setEntries(list.map(file=>({file,path:file.webkitRelativePath.slice(root.length+1),name:file.name,size:file.size})));setMessage(`${list.length.toLocaleString()} files available in ${root}. Paste the filename list next.`);}
  function review(){try{const found=matchList(entries,text);setRows(found);setChoices({});setAck(false);setResult(null);setError('');setPage(0);setFilter('all');setMessage(found.length?`${found.length} distinct names checked. Review the matches below.`:'The list has no filenames.');}catch(e){setRows(null);setError((e as Error).message);}}
  function changeChoice(row:MatchRow,value:string[]){setChoices(old=>({...old,[row.name]:value}));setResult(null);setAck(false);setMessage('Selection changed. Create a new ZIP after reviewing.');setError('');}
  const selected=rows?selectedPaths(rows,choices):[],set=new Set(selected),bytes=entries.reduce((n,e)=>n+(set.has(e.path)?e.size:0),0);
  const missing=rows?.filter(r=>!r.candidates.length).length||0,pending=rows?.filter(r=>unresolved(r,choices)).length||0,skipped=rows?.filter(r=>r.candidates.length&&!unresolved(r,choices)&&!rowSelection(r,choices).length).length||0;
  const issue=rows?bundleProblem(entries,rows,choices):'';
  const partial=!!(missing||skipped);const filtered=(rows||[]).filter(r=>filter==='all'||(filter==='missing'&&!r.candidates.length)||(filter==='multiple'&&r.candidates.length>1));const pages=Math.max(1,Math.ceil(filtered.length/25));const shown=filtered.slice(page*25,page*25+25);
  async function build(){if(!rows||busy||issue||partial&&!ack)return;const controller=new AbortController();abort.current=controller;setBusy(true);setError('');setResult(null);try{const out=await createBundle(entries,rows,choices,folder,controller.signal,(done,total)=>setMessage(`Preparing ZIP: ${size(done)} of ${size(total)}…`));setResult(out);setMessage(`ZIP ready: ${selected.length} files and report.json. Download and check the report.`);}catch(e){setMessage('');setError(controller.signal.aborted?'ZIP cancelled. Your source files are unchanged.':(e as Error).message);}finally{setBusy(false);abort.current=null;}}
  return <ToolFrame current="/file-list-pick" number="009 / FILES" title="File list pick" intro="Paste the names. Review the matches. Take just the files you need.">
    <section className="pick-inputs" aria-label="File selection workspace"><div className="file-pick"><label htmlFor="source-folder"><span className="step">01</span> Choose the source folder</label><input ref={picker} id="source-folder" type="file" multiple {...{webkitdirectory:''}} disabled={busy} onChange={e=>choose(e.target.files)}/><p>Includes subfolders. File contents stay in your browser; originals are never changed.</p><p className="pick-folder">{folder?`${folder} · ${entries.length.toLocaleString()} files`:'Choose a local folder to begin.'}</p><p className="small-note">Desktop browser recommended. Up to 10,000 source files; up to 64 MiB in each selected bundle.</p></div><div className="file-pick"><label htmlFor="file-names"><span className="step">02</span> Paste full filenames</label><textarea id="file-names" value={text} disabled={busy} onChange={e=>{setText(e.target.value);invalidate();}} spellCheck={false} placeholder={'photo 01.jpg\ninvoice.pdf\n선택.txt'} aria-describedby="pick-rules"/><p id="pick-rules">One filename per line, including its extension. Case and spaces must match. Empty lines are ignored.</p><div className="review-actions"><Button disabled={busy||!entries.length||!text} onClick={review}>Review matches</Button><Button variant="ghost" disabled={busy||!entries.length&&!text} onClick={()=>{invalidate();setEntries([]);setFolder('');setText('');if(picker.current)picker.current.value='';}}>Clear</Button></div></div></section>
    <div className="review-actions pick-example"><Button variant="outline" disabled={busy} onClick={example}>Try a small example</Button><span className="small-note">Four invented text files. No folder access needed.</span></div>
    <output className="status" aria-live="polite">{message||'Your folder and list are processed locally.'}</output>{error&&<p className="error" role="alert">{error}</p>}
    {rows&&!!rows.length&&<><section className="pick-summary" aria-label="Match summary"><div><strong>{selected.length}</strong><span>files selected</span></div><div><strong>{missing}</strong><span>names missing</span></div><div><strong>{pending}</strong><span>names need a choice</span></div><div><strong>{rows.reduce((n,r)=>n+r.lines.length-1,0)}</strong><span>repeated list lines</span></div></section>
    <section className="review"><div className="review-heading"><div><h2>Review before bundling</h2><p>Repeated names are grouped. Each source file is included once.</p></div><label className="pick-filter">Show <select value={filter} disabled={busy} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All names</option><option value="missing">Missing names</option><option value="multiple">Multiple matches</option></select></label></div>
      {shown.length?shown.map(row=><article className="pick-match" key={row.name}><div><strong className="pick-name">{row.name}</strong><p className="small-note">List {row.lines.length===1?'line':'lines'} {row.lines.join(', ')}{row.lines.length>1?' · repeated name':''}</p><span className={'pick-state '+(!row.candidates.length?'pick-missing':'')}>{!row.candidates.length?'Not found in this folder':unresolved(row,choices)?`${row.candidates.length} matches — choose or skip`:rowSelection(row,choices).length?`${rowSelection(row,choices).length} selected`:'Skipped'}</span></div><div>{row.candidates.length?<><div className="pick-candidates">{row.candidates.map(path=><label key={path}><input type="checkbox" disabled={busy} checked={rowSelection(row,choices).includes(path)} onChange={e=>changeChoice(row,e.target.checked?[...rowSelection(row,choices),path]:rowSelection(row,choices).filter(p=>p!==path))}/><span>{path}</span></label>)}</div>{row.candidates.length>1&&<Button variant="ghost" disabled={busy} onClick={()=>changeChoice(row,[])}>Skip this name</Button>}</>:<p className="small-note">Check spelling, extension and the chosen folder.{row.name!==row.name.trim()?' This line has leading or trailing whitespace; it was kept exactly as pasted.':''}{(row.name.includes('/')||row.name.includes('\\'))?' Paste a filename without folder paths.':''}</p>}</div></article>):<p className="empty-note">No names in this view.</p>}
      {pages>1&&<div className="pick-pager"><Button variant="outline" disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Previous</Button><span>Page {page+1} of {pages}</span><Button variant="outline" disabled={busy||page>=pages-1} onClick={()=>setPage(p=>p+1)}>Next</Button></div>}
    </section><section className="pick-export"><div><h2>{selected.length} files · {size(bytes)}</h2><p className="small-note">The ZIP contains <b>files/</b> with the original folder paths and <b>report.json</b> with selections and missing names. It bundles files without compressing or converting them.</p>{partial&&<label className="pick-ack"><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/><span>I understand that {missing} missing and {skipped} skipped names will not be included.</span></label>}{issue&&<p className="row-warning">{issue}</p>}</div><div className="review-actions"><Button disabled={busy||!!issue||partial&&!ack} onClick={build}>Create ZIP</Button>{busy&&<Button variant="outline" onClick={()=>abort.current?.abort()}>Cancel</Button>}<Button variant="outline" disabled={busy||!result} onClick={()=>result&&save(result,'hwanseek-selected-files.zip')}>Download ZIP</Button><Button variant="ghost" disabled={busy} onClick={()=>save(new Blob([JSON.stringify(makeReport(entries,rows,choices,folder),null,2)],{type:'application/json'}),'hwanseek-file-report.json')}>Download report</Button></div></section></>}
    <div className="notes-grid"><section><p className="eyebrow">HOW TO USE</p><h2>A filename list becomes a file bundle.</h2><ol><li>Choose a folder and paste full filenames, one per line.</li><li>Review missing names. For multiple matches, select the paths you want or skip the name.</li><li>Create and download the ZIP. Open the report and check the files before sending them.</li></ol><p>Starting with photos? Use <Link href="/photo-sheet">Photo Sheet</Link> to share a filename overview first. Keep the original display filenames if you want to use them here.</p></section><section><p className="eyebrow">WHERE IT STOPS</p><h2>Exact names, local files.</h2><p>This does not search cloud accounts, recognize images, guess typos, or fetch missing originals. Case and Unicode spelling are not normalized. Unsafe or conflicting output paths are blocked. Files keep their bytes; folder permissions, empty folders and filesystem dates are not copied. Larger batches need a desktop tool.</p></section></div><details className="privacy"><summary>Privacy and existing alternatives</summary><p>Chosen files and pasted names are kept in this page’s memory. This tool sends no file contents or names to a server and uses no AI service or browser storage. Hosting still involves normal page requests. Reloading clears the selection.</p><p>Already use Capture One? Its <a href="https://support.captureone.com/hc/en-us/articles/360002486138-Selecting-images">Filename List selection</a> may cover your photo workflow. <a href="https://www.voidtools.com/forum/viewtopic.php?t=10633">Everything 1.5 file lists</a> are another option for desktop searching.</p></details>
  </ToolFrame>;
}
