'use client';
import {useEffect,useRef,useState} from 'react';
import {ToolFrame} from '@/components/tool-frame';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {PhotoPicker,PhotoPrivacy,usePhotos} from '@/components/photo-workbench';
import {sizedJpeg,download,type SizedImage} from '@/lib/image-browser';
import {outputNames} from '@/lib/image-core';
export default function Review(){
  const [kb,setKb]=useState('200'),[width,setWidth]=useState('1200'),[result,setResult]=useState<(SizedImage&{url:string})|null>(null),[full,setFull]=useState(false);const url=useRef('');
  function invalidate(){p.setMessage('Settings changed. Create a new preview before saving.');p.setError('');if(url.current)URL.revokeObjectURL(url.current);url.current='';setResult(null);}
  useEffect(()=>()=>{if(url.current)URL.revokeObjectURL(url.current);},[]);
  const p=usePhotos(1,invalidate),photo=p.photos[0];const originalUrl=useRef('');const [source,setSource]=useState('');
  useEffect(()=>{if(originalUrl.current)URL.revokeObjectURL(originalUrl.current);originalUrl.current=photo?URL.createObjectURL(photo.file):'';setSource(originalUrl.current);return()=>{if(originalUrl.current)URL.revokeObjectURL(originalUrl.current);};},[photo]);
  async function generate(){if(p.busy||!photo)return;invalidate();p.setBusy(true);p.setError('');try{const r=await sizedJpeg(photo,Number(kb)*1000,Number(width),p.setMessage);if(!p.alive.current)return;url.current=URL.createObjectURL(r.blob);setResult({...r,url:url.current});p.setMessage(r.passes?'The JPG meets your entered size and width limits. Check readability before saving.':'No passing result was found within the quality and resize limits. Try a larger file allowance.');}catch(e){p.setError((e as Error).message);p.setMessage('');}finally{if(p.alive.current)p.setBusy(false);}}
  return <ToolFrame current="/image-size-check" number="007 / IMAGES" title="Image size check" intro="Set the limits. Measure the file. Check the detail.">
    <PhotoPicker busy={p.busy} limit={1} onChoose={p.choose} onClear={p.clear} count={p.photos.length}/>
    <section className="review"><div className="control-body"><div className="number-row"><label>Maximum size (KB)<Input type="number" min={1} max={20000} value={kb} disabled={p.busy} onChange={e=>{setKb(e.target.value);invalidate();}}/></label><label>Maximum width (px)<Input type="number" min={16} max={4096} value={width} disabled={p.busy} onChange={e=>{setWidth(e.target.value);invalidate();}}/></label></div><p className="small-note">1 KB = 1,000 bytes. Output: JPG on white. The photo is never enlarged. If needed, both dimensions shrink in proportion.</p><Button disabled={p.busy||!photo} onClick={generate}>Create JPG candidate</Button></div></section>
    <p className="status" role="status">{p.message||'Choose an image to begin.'}</p>{p.error&&<p role="alert" className="error">{p.error}</p>}
    {result&&<section className={'size-verdict '+(result.passes?'passed':'failed')} aria-label="Result checks"><h2>{result.passes?'Entered limits met':'File size limit not met'}</h2><p><strong>{result.blob.size.toLocaleString()} bytes</strong> / {(Number(kb)*1000).toLocaleString()} allowed · {result.width} × {result.height} pixels · JPG</p><p>Requested encoder quality: {Math.round(result.quality*100)}%. This is a setting, not a measured visual-quality score.</p><Button onClick={()=>download(result.blob,outputNames([photo.name],'jpg')[0])}>{result.passes?'Download JPG':'Download candidate (over limit)'}</Button></section>}
    {photo&&<><div className="review-actions image-view-controls"><Button variant="outline" onClick={()=>setFull(!full)}>{full?'Fit previews to panels':'Inspect at actual pixels'}</Button><span className="small-note">At actual pixels, scroll each panel to inspect details.</span></div><div className={'workspace image-comparison size-comparison '+(full?'actual-pixels':'')}><div className="editor-panel"><div className="panel-top">Original · {photo.width} × {photo.height} · {photo.file.size.toLocaleString()} bytes</div><div className="image-scroll"><img src={source} alt={`Original ${photo.name}`}/></div></div><div className="editor-panel result-panel"><div className="panel-top">JPG candidate{result&&` · ${result.width} × ${result.height}`}</div><div className="image-scroll">{result?<img src={result.url} alt="JPG candidate for visual comparison"/>:<p>Create a candidate to compare it here.</p>}</div></div></div></>}
    <div className="notes-grid"><section><p className="eyebrow">HOW TO USE</p><h2>Use the site's stated limits.</h2><ol><li>Enter the maximum file size and width required.</li><li>Create a candidate and inspect faces, text, and edges.</li><li>Download a copy and check the receiving site's other rules.</li></ol></section><section><p className="eyebrow">WHERE IT STOPS</p><h2>File checks are not acceptance promises.</h2><p>This checks only your entered limits. It does not validate official photo dimensions, minimum resolution, identity, document content, or a site's upload rules. JPG removes transparency; metadata and profiles are not preserved. The bounded search may fail and does not guarantee the best possible compression. Repeated compression can degrade detail.</p></section></div><PhotoPrivacy/>
  </ToolFrame>;
}
