'use client';
import {useMemo,useRef,useState} from 'react';
import {ToolFrame} from '@/components/tool-frame';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {DEFAULT_SHIFTS,EXAMPLE_ROW,parseRow,reviewPlan,createCalendar,type Shift} from '@/lib/shift-calendar';
import './style.css';
const kinds=[{value:'work',label:'Work shift'},{value:'off',label:'Day off — skip'}];
export default function Review(){
  const [month,setMonth]=useState('2026-09'),[text,setText]=useState(EXAMPLE_ROW),[zone,setZone]=useState('Asia/Seoul'),[shifts,setShifts]=useState<Shift[]>(DEFAULT_SHIFTS),[message,setMessage]=useState('Synthetic example — replace the month, row, hours, and work time zone.'),[busy,setBusy]=useState(false);
  const version=useRef(0);function changed(){version.current++;setMessage('');}
  const codes=useMemo(()=>{try{const cells=parseRow(text).cells;if(cells.length>31)return [];return [...new Set(cells.map(c=>c.trim()).filter(c=>!!c&&c.length<=32))];}catch{return [];}},[text]);
  const plan=useMemo(()=>({month,text,zone,shifts:shifts.filter(s=>codes.includes(s.code))}),[month,text,zone,shifts,codes]);
  const result=useMemo(()=>reviewPlan(plan),[plan]);
  function update(code:string,patch:Partial<Shift>){changed();setShifts(old=>{const found=old.find(s=>s.code===code);return [...old.filter(s=>s.code!==code),{code,kind:'work' as const,start:'',end:'',...found,...patch}];});}
  async function download(){if(busy||result.errors.length)return;const token=version.current;setBusy(true);setMessage('');try{const value=await createCalendar(plan);if(token!==version.current){setMessage('The plan changed while preparing the file. Review the new result and download again.');return;}const url=URL.createObjectURL(new Blob([value],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`work-shifts-${month}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage('Calendar file prepared. Import into a separate calendar and inspect its dates and times. Re-importing can duplicate events.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <ToolFrame current="/shift-calendar-review" number="010 / CALENDAR" title="Shift calendar review" intro="One row for the month. Check every date, then take it to your calendar.">
    <div className="shift-workspace"><section className="shift-input" aria-labelledby="paste-title"><div className="shift-section-title"><h2 id="paste-title">Your monthly row</h2><Button variant="ghost" onClick={()=>{changed();setMonth('2026-09');setText(EXAMPLE_ROW);setZone('Asia/Seoul');setShifts(DEFAULT_SHIFTS);setMessage('Synthetic September example loaded.');}}>Load example</Button></div>
      <div className="shift-settings"><label>Month<input type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{changed();setMonth(e.target.value);}}/></label><label>Work time zone<input value={zone} list="work-zones" onChange={e=>{changed();setZone(e.target.value);}} placeholder="Europe/London"/><datalist id="work-zones">{['Asia/Seoul','Asia/Tokyo','Asia/Kolkata','Europe/London','Europe/Berlin','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Australia/Sydney','UTC'].map(z=><option key={z} value={z}/>)}</datalist></label></div>
      <label htmlFor="shift-row">Codes, from day 1 to the last day</label><textarea id="shift-row" spellCheck={false} value={text} onChange={e=>{changed();setText(e.target.value);}} aria-describedby="row-help"/>
      <p id="row-help" className="shift-hint">Paste your row from a spreadsheet, or use spaces, commas, or one code per line. Include every day. Empty tab/comma cells stay empty; use OFF for days off. You may include a first row numbered 1, 2, 3… through the last day. No names or totals.</p>
      <h2>What each code means</h2><p className="shift-hint">24-hour clock. An earlier end time means the next day. Codes are case-sensitive.</p>
      <div className="shift-definitions">{codes.map(code=>{const s=shifts.find(s=>s.code===code);return <div className="shift-definition" key={code}><strong title={code}>{code}</strong><Select value={s?.kind||'work'} items={kinds} onValueChange={value=>{if(value)update(code,{kind:value as 'work'|'off'});}}><SelectTrigger aria-label={`${code} event type`}><SelectValue/></SelectTrigger><SelectContent>{kinds.map(k=><SelectItem key={k.value} value={k.value}>{k.label}</SelectItem>)}</SelectContent></Select>{s?.kind!=='off'&&<div className="shift-times"><label>Start<input aria-label={`${code} start time`} type="time" value={s?.start||''} onChange={e=>update(code,{start:e.target.value})}/></label><span aria-hidden="true">→</span><label>End<input aria-label={`${code} end time`} type="time" value={s?.end||''} onChange={e=>update(code,{end:e.target.value})}/></label></div>}</div>;})}</div>
    </section><section className="shift-review" aria-labelledby="review-title"><div className="shift-section-title"><h2 id="review-title">Dates beside your codes</h2><span>{result.days.length} / {result.count||'—'} days</span></div>
      <div className={result.errors.length?'shift-banner issue':'shift-banner ready'} role="status">{result.errors.length?`${result.errors.length} issue${result.errors.length===1?'':'s'} to resolve`:`${result.workCount} work events · ${result.days.filter(d=>d.off).length} days off`}</div>
      {!!result.errors.length&&<ul className="shift-errors">{result.errors.slice(0,4).map((e,i)=><li key={i}>{e}</li>)}{result.errors.length>4&&<li>Remaining issues are marked beside their dates below.</li>}</ul>}
      <div className="shift-day-list">{result.days.map(day=><div className={'shift-day '+(day.error?'has-error':day.off?'is-off':'')} key={day.date}><time>{day.date.slice(5)}</time><code title={day.original}>{day.original||'∅'}</code><div>{day.error?<span>{day.error}</span>:day.off?<span>Day off · no event</span>:<><strong>{day.start?.slice(11)} → {day.end?.slice(11)}{day.end?.slice(0,10)!==day.date&&<em> +1 day</em>}</strong><small>Ends {day.end}</small></>}</div></div>)}</div>
      <Button onClick={download} disabled={busy||!!result.errors.length||!result.workCount}>{busy?'Preparing…':'Download calendar (.ics)'}</Button><p className="shift-hint">Import once into a separate calendar. This file does not update itself when your employer changes the rota. Re-importing may create duplicates; changed events do not remove old ones.</p>
    </section></div><p className="status" role="status">{message}</p>
    <div className="notes-grid"><section><h2>Check the first, last, and night shift</h2><p>Before relying on the import, compare those events with the original schedule in the work time zone. Calendar apps may display the same event in a different local zone.</p><p><a href="https://support.google.com/calendar/answer/37118?co=GENIE.Platform%3DDesktop&hl=en">Google Calendar import steps ↗</a></p></section><section><h2>Where this stops</h2><p>One whole month, one shift per day. No photos, OCR, live sync, shift swaps, breaks, or 24-hour shifts. Ambiguous or nonexistent times during clock changes block the file; resolve those schedules directly in your calendar.</p><p>Matching the number of cells cannot prove that the source row is correct. Compare dates before importing.</p></section></div>
    <details className="privacy"><summary>What happens to my schedule?</summary><p>The row is processed in this browser tab. It is not uploaded, sent to AI, or saved in browser storage by this tool. Reloading clears your edits. The downloaded file contains your shift codes and times. Ordinary page requests still reach the hosting provider.</p></details>
  </ToolFrame>;
}
